version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: ['/usr/src/app/entrypoint.sh'] # new
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    env_file: .env_test
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    command: mongod --noauth
